INSERT INTO users VALUES (NULL,'Liisi', 'K',0);
INSERT INTO users VALUES (NULL,'Mikk', 'V',1);
INSERT INTO users VALUES (NULL,'Mikk2', 'V',2);
INSERT INTO users VALUES (NULL,'Mikk3', 'V',3);

INSERT INTO types VALUES (NULL,'MANAGER');
INSERT INTO types VALUES (NULL,'USER');
INSERT INTO types VALUES (NULL,'ADMIN');
INSERT INTO types VALUES (NULL,'BOSS');